ribru17/ts_query_ls

- Cargo.lock
- Cargo.toml
- src/main.rs
It's not entirely clear to me what was causing the previous logging implementation to have issues. Only logs with `MessageType::ERROR` would be logged (at least in neovim). This could be partially addressed by using a `tracing_subscriber` logger (as suggested here: https://github.com/ebkalderon/tower-lsp/issues/423). The server's logs would show up if the level was set to `TRACE`, but then so would every single message exchanged between the lsp client and server. Swapping out the calls to `self.client.log_message()` with the `log` crate's macros, as well as to the `tracing_subscriber` changes seems to remedy things. Log file after start up:
```log
[START][2024-11-17 23:44:15] LSP logging initiated
[ERROR][2024-11-17 23:44:15] .../vim/lsp/rpc.lua:764	"rpc" …
```
> fix: enable non-error logs

- README.md
- src/main.rs
- src/util.rs
Implements goto definition for captures. The approach I took was just:
1. Collect all references for the capture in question
2. Go to the earliest occurring instance
This rests on the assumption that captures are always defined before they're used, which I *think* is true but don't know for certain. This approach could potentially be slow for large numbers of captures as it requires iterating over every single reference to the capture. However in practice this shouldn't be an issue, as usually a capture is referenced only once or twice within a query definition.
Quick demo gif:
(Please excuse the flickering, it only shows up in the recording and I have no idea what's causing it :upside_down_face:)
> feat: implement goto definition for captures

- Cargo.toml
- src/main.rs
- src/util.rs
The first commit just fixes some of clippy's more pedantic lints. I wanted to note that while the explicit imports are arguably uglier than the wildcard `*` and obviously more verbose, the wildcard imports have bitten me before due to similarly named types between various lsp-related crates. 
The second just swaps "AST" for "CST" to match the verbage used in tree-sitter's [docs](https://tree-sitter.github.io/tree-sitter/). (This is such an ackshually change I kinda feel bad about it, but it may help prevent some future confusion. Feel free to disregard :laughing:)
Next todo...tests! :)
> misc. cleanup

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/main.rs
- src/test.rs
(Marking as a draft for now until some questions/ decisions are settled)
Opening this as a fairly rough proof of concept for adding some unit tests to the project. In particular, this adds some coverage for the `get_references` function. The current implementation takes in a source string with a single `<CURSOR>` marker indicating where the cursor should be, and 0 or more `<REF>` markers indicating expected reference points. Said ref markers need to come directly before the capture they mark, i.e. `<REF>@foo.cap`. These markers are collected and translated into positions, the server's `get_references` function is called, and then the two sets of references are compared. I tried adding some dev helpers in the test implementation to aid in adding more tests as well. For example, what if we …
> feat: add tests

- src/handlers/document_symbol.rs
- src/handlers/mod.rs
- src/main.rs
Returns all captures in a document, with their broader range being the nodes they capture. E.g. for:
```query
(foo
(bar)) @cap
```
the `@cap` variable's broad range is the range of the whole `(foo (bar ...` pattern.
Work towards #37
> feat: document symbols

- src/handlers/formatting.rs
- src/util.rs
Now tree iteration uses one cursor formed at the root, and all children iterate using that one cursor. Previously, each child would allocate its own `TreeCursor` which was very expensive.
> fix: prevent lots of cursor allocations during formatting

- README.md
- src/handlers/did_open.rs
- src/main.rs
- src/util.rs
Allows the server to act as a standalone linter for query files. Useful
for CI.
Note that the linter ignores Rust-binding specific predicate errors,
since predicate usage is largely dependent on the implementation on the
consumer's side.
Closes #45
> feat: standalone linter

- Cargo.lock
Prior version had safety vulnerabilities
> chore: bump tokio

- .github/workflows/ci.yml
- README.md
- schemas/config.json
- src/handlers/did_change.rs
- src/handlers/did_change_configuration.rs
- src/handlers/did_open.rs
- src/handlers/initialize.rs
- src/lib.rs
- src/main.rs
- src/test_helpers.rs
- src/util.rs
Currently not support by the `check` subcommand, nor autocompletions or hover.
`check` support requires https://github.com/tree-sitter/tree-sitter/pull/4384, the other TODOs can be done now
> feat: partial support for capture name validation

- src/handlers/completion.rs
- src/handlers/diagnostic.rs
- src/main.rs
- src/test_helpers.rs
This commit also improves the existing capture completions by adding `TextEdit` support, meaning there are no longer any dodgy semantics regarding whether or not the completion should slurp up the preceding `@` sign.
> feat: completions for valid captures

- README.md
- schemas/config.json
- src/handlers/diagnostic.rs
- src/handlers/hover.rs
- src/lib.rs
Also renames the `varargs` type to `variadic`, because it makes more sense. Not breaking becuz no release :rocket emoji:
> feat: hover for predicates, directives

- README.md
- src/main.rs
Lints are independent of parser objects, and run solely based off of the server configuration. Checks require access to the language object to attempt a full query compilation.
Note that this commit makes it so that `check` no longer lints by default.
Closes #90
> feat!: separate "lints" from "checks"

- queries/formatting_test_files/after_missing.scm
- queries/formatting_test_files/before_complex.scm
- queries/formatting_test_files/before_missing.scm
- src/handlers/formatting.rs
The problem was we only stopped recurring when a node had no *named* children. A blank MISSING node, however, has no named children but a few unnamed children. This meant the entire node was treated as one "string unit" so spaces inside it weren't being collapsed. This commit fixes the formatter logic and adds some more test cases for this.
> fix(formatter): correct blank MISSING node format

- queries/formatting_test_files/after_complex.scm
- queries/formatting_test_files/before_complex.scm
- src/handlers/formatting.rs
- src/main.rs
`format` applied a final newline to files before the actual formatter did so. Now it does, but we must remove the `format` patch lest two newlines be applied to files.
Additionally, strings should go back to having their inner content untouched, as they can have other named nodes inside them, like escape sequences.
> fix(formatter): fix subcommand, string formatting

- Cargo.lock
- Cargo.toml
- src/lib.rs
- xtask/Cargo.toml
Removes an old, unused dependency and only includes schemars in the xtask builds (as it is only used for schema generation)
> chore: prune dependencies

- Cargo.lock
- Cargo.toml
- tests/format.rs
This adds some basic CLI formatting tests as discussed in #94.
I held off on adding tests for the `check` and `lint` subcommands because I wasn't sure exactly what we'd want to test against and what the corpus should look like. Should we be checking the raw text output? Exit code? I'm ok with whatever, but thought it warranted a discussion first. The same goes for `format --check`.
I bumped the `rstest` dependency from 0.23.0 to 0.25.0 to access the `context` macro. This was useful in giving each test case its own isolated test directory. This isn't strictly necessary, but added it for the following reasons
- Good basic hygiene - Different test cases shouldn't have a chance of interacting with one another.
- If we want to add a test case for formatting directories instead of single files, …
> feat(test): CLI format test

- src/cli/lint.rs
- src/handlers/completion.rs
- src/handlers/diagnostic.rs
- src/handlers/did_open.rs
- src/handlers/execute_command.rs
- src/handlers/hover.rs
- src/handlers/initialize.rs
- src/handlers/semantic_tokens_full.rs
- src/main.rs
- src/test_helpers.rs
This decouples language information from document information, reducing memory in the case that multiple documents are open which all share the same query language. This refactor also makes it easier to share the language object in the future.
> refactor: extract language data into a separate struct

- Cargo.lock
- Cargo.toml
- src/cli/check.rs
- src/cli/format.rs
- src/cli/lint.rs
- src/handlers/diagnostic.rs
- src/handlers/execute_command.rs
- src/main.rs
- tests/format.rs
- tests/lint.rs
This refactor allows the diagnostics to be asynchronous with no worries
of deadlock. This, of course, required a lot of changes because of
function coloring. As such, CLI methods are now asynchronous. This
commit also removes the dependency on `rayon`, and adds the `futures`
crate.
> refactor: make diagnostics thread safe

- README.md
- src/cli/check.rs
- src/cli/lint.rs
- src/handlers/did_open.rs
- src/main.rs
This commit makes it so that `check` is always a superset of `lint`, and removes the `--lint` flag from `check`, which is why it is marked as breaking. `check` will now always lint, and will display errors for each pattern (rather than just the first error, as before).
Closes #108
> fix!: display all errors in `ts_query_ls check`

- queries/query/diagnostics.scm
- src/handlers/diagnostic.rs
- src/handlers/did_open.rs
This commit allows node types to be recognized if they have an unnecessary preceding backslash. It also issues a warning that the backslash is not necessary.
See https://github.com/tree-sitter/tree-sitter/blob/31b9717ca3d674d6166f8e4aa17e7927b027c1e1/lib/src/query.c#L2042C7-L2058C8
> fix: account for superfluous escape sequences

- src/handlers/code_action.rs
- src/handlers/diagnostic.rs
- tests/lint.rs
This lint also has a quickfix code action to remove it, but it's not advertised in the diagnostic message because it would become too verbose, and it's not often the proper fix.
> feat: lint for pointless patterns

- README.md
- queries/query/diagnostics.scm
- schemas/config.json
- src/handlers/diagnostic.rs
- src/lib.rs
Can be disabled, enabled by default
> feat(diagnostics): warn on unused underscore captures

- src/cli/check.rs
- src/cli/format.rs
- src/cli/lint.rs
- src/cli/mod.rs
- src/cli/profile.rs
- src/handlers/goto_definition.rs
- src/handlers/initialize.rs
- src/handlers/semantic_tokens.rs
- src/main.rs
- src/util.rs
Adds support for:
- Semantic tokens for imported modules in `inherits` statements
- Goto definition for modules
TODO (separate PR(s)):
- Diagnostics (conceptually harder)
- Documentation (mention the modeline format, restrictions, etc.)
- Do not make release until this happens
- Support `workspace/symbol` requests (#37)
> Begin supporting `; inherits`

- schemas/config.json
- src/handlers/completion.rs
- src/handlers/did_change_configuration.rs
- src/lib.rs
- src/test_helpers.rs
- src/util.rs
Now language retrieval regexes are only compiled at deserialization time, rather than every time they need to be read. The same goes for the addition of the default regexes.
Now tests pass the initialization options in the initialization request, rather than setting the server field manually.
> refactor: configuration setting simplification

- README.md
- src/cli/check.rs
- src/cli/lint.rs
- src/handlers/diagnostic.rs
- src/handlers/did_change.rs
- src/handlers/did_open.rs
- src/handlers/goto_definition.rs
- src/main.rs
- src/util.rs
Also adds a `--workspace` flag to `check` and `lint` to specify the workspace directory where query modules are searched when `; inherits` is used. Defaults to the current dir.
Closes #151
> feat: support `; inherits` in CLI commands

- src/cli/check.rs
- src/cli/lint.rs
- src/handlers/did_open.rs
- src/handlers/initialize.rs
- src/main.rs
- src/util.rs
This aligns the types to rust's own path types, rather than the LSP-specific URI type. This simplifies a lot of the code, which performed a lot of redundant URI to path conversion.
> refactor: store workspace URIs as PathBufs rather than Urls

- Cargo.lock
- Cargo.toml
- README.md
- src/util.rs
Internally, this swaps walkdir for the heavier, more feature-rich and parallelizable ignore crate when searching for `.scm` files.
> feat: respect gitignore, hidden files when searching workspace

- queries/test_workspace/queries/cpp/test.scm
- src/handlers/completion.rs
- src/test_helpers.rs
- src/util.rs
Also adds a test workspace folder which can be used in other places for better testing with workspace-related features and `; inherits`
> feat(completion): support for `inherits:` and module names

- src/handlers/workspace_symbol.rs
I guess I should remember to rebase all my branches before merging...
> fix: wrong type for workspace URIs when finding symbols

- Cargo.lock
- Cargo.toml
- src/cli/format.rs
- tests/format.rs
I noticed the cli tool silently fails when invoking `format` on a malformed file. (I was testing out the coloring logic by adding a line to a .`scm` file that started with `@@`.) Happy to revert if this is the intended behavior.
Edit: Ah, I see this is already covered in a test. I could revert the second commit and keep the existing behavior, or change the test to expect a non-empty output (and maybe a different non-zero exit code?). Which way would you like to go forward? 🙂
- Closes #98
> feat(cli): print diff when using format --check

- queries/test_workspace/queries/cpp/test.scm
- src/handlers/code_action.rs
- src/handlers/completion.rs
- src/handlers/diagnostic.rs
- src/handlers/did_change.rs
- src/handlers/did_change_configuration.rs
- src/handlers/did_open.rs
- src/handlers/document_highlight.rs
- src/handlers/document_symbol.rs
- src/handlers/formatting.rs
- src/handlers/goto_definition.rs
- src/handlers/hover.rs
- src/handlers/references.rs
- src/handlers/rename.rs
- src/handlers/selection_range.rs
- src/handlers/semantic_tokens.rs
- src/main.rs
- src/test_helpers.rs
This is a large refactor that separates the document population logic from the language population logic. This allows us to craft much more granular tests, such as ones that check for diagnostics when no languages are found. It also paves the way to using real language objects in tests, to provide full end-to-end coverage. Additionally, it allows tests to be fully workspace-aware, allowing coverage for workspace methods (e.g. workspace symbols), and for diagnostics which require importing files from the workspace.
It also removes the custom test document population logic with actual calls to `textDocument/didOpen`, giving full coverage for that notification.
> test: overhaul initialization logic

- README.md
- queries/test_workspace/queries/other/test.scm
- src/cli/profile.rs
- src/handlers/code_action.rs
- src/handlers/completion.rs
- src/handlers/diagnostic.rs
- src/handlers/did_change.rs
- src/handlers/did_change_configuration.rs
- src/handlers/did_open.rs
- src/handlers/document_highlight.rs
- src/handlers/document_symbol.rs
- src/handlers/formatting.rs
- src/handlers/goto_definition.rs
- src/handlers/hover.rs
- src/handlers/references.rs
- src/handlers/rename.rs
- src/handlers/selection_range.rs
- src/handlers/semantic_tokens.rs
- src/main.rs
- src/test_helpers.rs
- src/util.rs
This allows us to have true end-to-end coverage for language loading, at least just for the `query` language. In the future other languages can be added as dev dependencies.
This allows for another massive refactor of the test logic, removing custom test helper hacks, unnecessary optionals used by mocks, and removes lots of redundant code, replacing it with calls to the actual server method handlers (which now have increased test coverage).
> test: use query language object in mock tests

- src/cli/format.rs
- src/cli/lint.rs
- src/handlers/did_change.rs
- src/handlers/did_open.rs
- src/handlers/document_highlight.rs
- src/handlers/goto_definition.rs
- src/handlers/references.rs
- src/handlers/workspace_symbol.rs
- src/util.rs
Also, remove some useless parser instantiations in some handlers that don't need it.
> refactor: reduce parser allocations by keeping a static object

- src/handlers/did_change.rs
- src/handlers/did_open.rs
- src/handlers/rename.rs
- src/main.rs
- src/util.rs
Documents which are populated only because other documents have imported them, but have not been opened by the editor itself, should not have a fake -1 sentinel version number. Rather, the number should be `None` for slightly better correctness.
> refactor: store empty version for unopened documents

- src/handlers/code_action.rs
- src/handlers/completion.rs
- src/handlers/diagnostic.rs
- src/handlers/did_change.rs
- src/handlers/did_change_configuration.rs
- src/handlers/did_close.rs
- src/handlers/did_open.rs
- src/handlers/did_save.rs
- src/handlers/document_highlight.rs
- src/handlers/document_symbol.rs
- src/handlers/formatting.rs
- src/handlers/goto_definition.rs
- src/handlers/hover.rs
- src/handlers/initialize.rs
- src/handlers/references.rs
- src/handlers/rename.rs
- src/handlers/selection_range.rs
- src/handlers/semantic_tokens.rs
- src/handlers/shutdown.rs
- src/handlers/workspace_symbol.rs
- src/main.rs
- src/test_helpers.rs
- src/util.rs
We can now test that the server sent certain notifications/requests to the client. Also prevents tests from hanging upon notifying the client. Great!
> test: mock client to record notification events
